name: Selenium Tests with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests (ignore failures so report still generates)
        run: mvn clean test -Dmaven.test.failure.ignore=true

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Deploy Allure Report to SLT server
        if: always()
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SLT_HOST }}
          username: ${{ secrets.SLT_USER }}
          password: ${{ secrets.SLT_PASS }}
          source: "target/allure-report/*"
          target: "/var/www/html/selenium-report"
