name: Selenium CI with Allure Report

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Run Maven tests (ignore failures so report still generates)
      - name: Run Tests
        run: mvn clean test -Dmaven.test.failure.ignore=true

      # 4. Install Allure CLI directly (bypassing PPA)
      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.26.0
          wget https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.tgz
          tar -zxvf allure-$ALLURE_VERSION.tgz -C $HOME/
          echo "$HOME/allure-$ALLURE_VERSION/bin" >> $GITHUB_PATH
      - name: Check Allure version
        run: allure --version

      # 5. Generate Allure report
      - name: Generate Allure Report
        run: allure generate target/allure-results -o target/allure-report --clean

      # 6. List report contents (for debugging / SCP safety)
      - name: List Allure report contents
        run: ls -R target/allure-report

      # 7. Upload Allure report as GitHub artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      # 8. Deploy Allure report to SLT server (safe path)
      - name: Deploy Allure Report to SLT
        if: always()
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SLT_HOST }}
          username: ${{ secrets.SLT_USER }}
          password: ${{ secrets.SLT_PASS }}
          source: "target/allure-report/*"
          target: "/home/${{ secrets.SLT_USER }}/selenium-report"
