name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2
          
    - name: Run Tests
      run: mvn test || true # keep workflow running even if tests fail
      
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results
        
    - name: Check allure results
      run: ls -R target || echo "No results found"

  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        
    - name: Download Allure Results
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: target/allure-results  # Download directly to target/allure-results
        
    - name: Download previous history
      run: |
        git fetch origin gh-pages || true
        git checkout gh-pages -- history || echo "No previous history found"
        
    - name: Prepare Allure History
      run: |
        mkdir -p target/allure-results/history
        cp -r history/* target/allure-results/history/ || true
        
    - name: Generate Allure Report
      run: |
        mvn io.qameta.allure:allure-maven:report
        
    - name: 🚀 Display Report URL
      run: |
        echo "=============================================="
        echo "🎉 ALLURE REPORT READY!"
        echo "=============================================="
        echo "📊 Your report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "=============================================="
        echo "ℹ️  Report will be live in 2-3 minutes"
        echo "=============================================="
        
    - name: Prepare deployment directory
      run: |
        mkdir -p allure-report
        cp -r target/allure-report/* allure-report/ || echo "No report generated"
        
    - name: Save history for next run
      run: |
        mkdir -p history
        cp -r target/allure-report/history/* ./history/ || true
        
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        
    - name: Display Report URL
      run: |
        echo "🎉 Allure Report has been deployed!"
        echo "📊 View your report at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "🔗 Direct link: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html"
        
    - name: Comment PR with Report Link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 **Allure Test Report Generated!**\n\n📊 [View Report](https://Janeesha123.github.io/mmProAutomation/)\n\n*Report will be available in a few minutes after deployment completes.*'
          })
          
    - name: 🔗 Final Report Link
      run: |
        echo ""
        echo "🎯 CLICK TO VIEW YOUR REPORT:"
        echo "👉 https://Janeesha123.github.io/mmProAutomation/"
        echo ""
        
    - name: Add to Job Summary
      run: |
        echo "## 🎉 Allure Report Generated Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 [Click here to view your Allure Report](https://Janeesha123.github.io/mmProAutomation/)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Report URL: \`https://Janeesha123.github.io/mmProAutomation/\`" >> $GITHUB_STEP_SUMMARY
