name: Run Tests and Deploy Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn test || true   # keep workflow running even if tests fail

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

  deploy-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # ✅ Get old history from gh-pages branch
      - name: Download previous history
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages -- history || echo "No previous history found"

      # ✅ Copy history into new results
      - name: Prepare Allure History
        run: |
          mkdir -p allure-results/history
          cp -r history/* allure-results/history/ || true

      # ✅ Generate Allure Report
      - name: Generate Allure Report
        run: |
          mvn io.qameta.allure:allure-maven:report \
            -Dallure.results.directory=allure-results
          mkdir -p allure-report
          cp -r target/site/allure-maven-plugin/* allure-report/

      # ✅ Save history for next run
      - name: Save history
        run: |
          mkdir -p allure-report/history
          cp -r allure-report/history ./history || true

      # ✅ Deploy report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
