name: Run Tests and Generate Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          mvn allure:report
          mkdir -p target/allure-results/history
          cp -r target/allure-report/history/. target/allure-results/history/ || true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4   # ✅ v4 (not v3)
        with:
          name: allure-results
          path: target/allure-results

  deploy-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Final Allure Report
        run: |
          mvn allure:report -Dallure.results.directory=allure-results
          mkdir -p allure-report-history
          cp -r target/allure-report/* allure-report-history/

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report-history
